// loadLib("zsLibs/adapter/zs.wx.banner.js"), 
// loadLib("zsLibs/adapter/zs.platform.wx.js"), 
// loadLib("zsLibs/adapter/zs.platform.config.js"), 
loadLib("zsLibs/adapter/zs.eggknock.js"), 
loadLib("zsLibs/framework/fairygui.js"), 
loadLib("zsLibs/framework/zs.proxy.js"), 
loadLib("zsLibs/framework/crypto-js.js"), 
loadLib("zsLibs/framework/zs.log.js"), 
loadLib("zsLibs/framework/zs.resource.js"), 
loadLib("zsLibs/framework/zs.utils.js"), 
loadLib("zsLibs/framework/td-sdk.js"), 
loadLib("zsLibs/framework/zs.td.js"), 
loadLib("zsLibs/framework/zs.product.js"), 
loadLib("zsLibs/framework/zs.fgui.js"), 
loadLib("zsLibs/framework/zs.fsm.js"), 
// loadLib("zsLibs/framework/zs.platform.js"), 
loadLib("zsLibs/framework/zs.ui.js"), 
loadLib("zsLibs/framework/zs.exporter.js"), 
loadLib("zsLibs/framework/zs.network.js"), 
loadLib("zsLibs/framework/zs.core.js"), 
loadLib("zsLibs/framework/zs.base.js"), 
loadLib("zsLibs/framework/zs.scene.js"), 
loadLib("js/bundle.js");