window.zs = window.zs || {}, window.zs.laya = window.zs.laya || {}, function(E, _) {
    "use strict";
    class A {
        constructor() {}
    }
    A.NET_XHR_RESPONSE = zs.laya.XHRUtils.NET_XHR_RESPONSE, A.APP_SHOW = zs.laya.sdk.DeviceService.EVENT_ON_SHOW, 
    A.APP_HIDE = zs.laya.sdk.DeviceService.EVENT_ON_HIDE, A.APP_JUMP_CANCEL = "NAVIGATE_FAILED", 
    A.APP_JUMP_SUCCESS = "NAVIGATE_SUCCESS", A.AD_CONFIIG_LOADED = "AD_CONFIIG_LOADED", 
    A.UI_TOAST_MESSAGE = "UI_TOAST_MESSAGE", A.AD_VIDEO_PLAY = "EVENT_AD_VIDEO_PLAY", 
    A.AD_VIDEO_CLOSED = "EVENT_AD_VIDEO_CLOSED", A.LAUNCH_COMPLETED = "EVENT_LAUNCH_COMPLETED", 
    A.DATA_SETTING_UPDATE = "DATA_SETTING_UPDATE", A.DATA_LOGIN_INFO_UPDATE = "DATA_LOGIN_INFO_UPDATE", 
    A.GAME_SLEEP = "GAME_SLEEP", A.GAME_WAKEUP = "GAME_WAKEUP", A.GAME_HOME = "GAME_HOME", 
    A.GAME_PREPARE = "GAME_PREPARE", A.GAME_START = "GAME_START", A.GAME_WIN = "GAME_WIN", 
    A.GAME_FAILED = "GAME_FAILED", A.GAME_RELIVE = "GAME_RELIVE", A.GAME_OVER = "GAME_OVER", 
    A.GAME_NEXTRES_COM = "GAME_NEXTRES_COM", A.EGG_GET_AWARD = "EGG_GET_AWARD", A.OPEN_WIN_VIEW = "OPEN_WIN_VIEW", 
    A.OPEN_FAILED_VIEW = "OPEN_FAILED_VIEW", A.GAME_RESET_START = "GAME_RESET_START", 
    A.STORECFG_UPDATE = "STORECFG_UPDATE", A.STORE_SWITCH_TAB = "STORE_SWITCH_TAB", 
    A.STORE_USE_ITEM = "STORE_USE_ITEM", A.STORE_ITEM_UNLOCKED = "STORE_ITEM_UNLOCKED", 
    A.GOLD_UPDATE = "GOLD_UPDATE", A.COLLECT_GET_AWARD = "COLLECT_GET_AWARD", A.START_REWARD = "START_REWARD", 
    A.PLATFORM_ADD_COIN = "PLATFORM_ADD_COIN", A.RECORDER_VIDEO_RANK = "RECORDER_VIDEO_RANK", 
    _.ILaya.regClass(A), _.ClassUtils.regClass("zs.laya.game.EventId", A), _.ClassUtils.regClass("Zhise.EventId", A), 
    E.EventId = A;
}(window.zs.laya.game = window.zs.laya.game || {}, Laya);