loadLib("./libs/laya.core.js"),
  loadLib("./libs/laya.wxmini.js"),
  loadLib("./libs/laya.webgl.js"),
  loadLib("./libs/laya.ani.js"),
  loadLib("./libs/laya.filter.js"),
  loadLib("./libs/laya.html.js"),
  loadLib("./libs/laya.particle.js"),
  loadLib("./libs/laya.tiledmap.js"),
  loadLib("./libs/laya.ui.js");
