window.screenOrientation = "sensor_landscape",
    loadLib("libs/min/laya.core.min.js"),
    loadLib("libs/min/laya.ui.min.js"),
    loadLib("libs/min/laya.d3.min.js"),
    loadLib("adapter/zs.laya.base.js"),
    loadLib("adapter/zs.laya.js"),
    loadLib("adapter/zs.laya.wx.conf.js"),
    loadLib("adapter/zs.laya.wx.ad.js"),
    loadLib("adapter/zs.laya.sdk.js"),
    loadLib("adapter/zs.laya.banner.js"),
    loadLib("adapter/zs.laya.platform.js"),
    loadLib("adapter/zs.laya.zsapp.js"),
    loadLib("adapter/zs.laya.tdapp.js"),
    loadLib("js/bundle.js");